version: '3.8'

services:
  # Laravel (backend)
  backend:
    build:
      dockerfile: ./.docker-env/api/Dockerfile
    container_name: laravel-app
    restart: on-failure
    volumes:
      - ./api:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=finance
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: bash -c "if [ ! -f composer.json ]; then composer create-project --prefer-dist laravel/laravel .; fi && composer install && php-fpm"
    depends_on:
      - db
    networks:
      - app-network

  # Nuxt.js (frontend)
  frontend:
    build:
      dockerfile: ./.docker-env/web/Dockerfile
    container_name: nuxt-app
    restart: unless-stopped
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    command: sh -c "if [ ! -f package.json ]; then npx nuxi init .; fi && npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - app-network

  # Nginx for serving Laravel and Nuxt
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker-env/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - ./.docker-env/nginx/web.conf:/etc/nginx/conf.d/web.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # MySQL (Database)
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "./.docker-env/.db_data/mysql:/var/lib/mysql"
    networks:
      - app-network
    ports:
      - "192.168.10.10:3306:3306"

networks:
  app-network:
    driver: bridge